FROM node:20-alpine AS build

WORKDIR /app/frontend

COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci --no-update-notifier

COPY frontend /app/frontend

RUN npm run build --no-update-notifier

FROM nginx:alpine

COPY deploy/nginx/etaseneu.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

